
include: package:flutter_lints/flutter.yaml

analyzer: 
  exclude:
    - build/**
    - lib/*.g.dart
    - lib/*.freezed.dart

  language: 
    strict-raw-types: true
    strict-casts: true

linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_annotating_with_dynamic
    - avoid_classes_with_only_static_members
    - await_only_futures
    - cancel_subscriptions
    - cascade_invocations
    - prefer_expression_function_bodies
    - sort_pub_dependencies 
    - unnecessary_this
    - use_is_even_rather_than_modulo
    - void_checks