name: medi_support
description: A Medical information forum
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
