name: medi_support
description: A Medical information forum
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cached_network_image: ^3.0.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  go_router: ^14.1.4
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.3.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/
